# Changes here will be overwritten by Copier
_commit: v7.3.0-23-g37cff5f
_src_path: gh:eccenca/cmem-plugin-template
author_mail: cmempy-developer@eccenca.com
author_name: eccenca GmbH
github_page: https://github.com/eccenca/cmem-plugin-base
project_description: Base classes for developing eccenca Corporate Memory plugins.
project_slug: cmem-plugin-base
project_type: generic
pypi: true

