---
default:
  image: docker-registry.eccenca.com/eccenca-python:v3.7.0

stages:
  - test

check-bandit:
  stage: test
  script:
    - task check:bandit

check-flake8:
  stage: test
  script:
    - task check:flake8

check-mypy:
  stage: test
  script:
    - task check:mypy

check-pylint:
  stage: test
  script:
    - task check:pylint

check-pytest:
  stage: test
  script:
    - task check:pytest

check-safety:
  stage: test
  script:
    - task check:safety
