---
repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint
        exclude: '^tests/.*$'
        language: system
        types: [python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-xml
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-case-conflict
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
        language_version: python3

